### ISSUE TITLE
Rename to husk

### ISSUE THREAD

**Issue by benogle** [atom/electron-starter#52]
`atom-shell-starter` is a pretty rough name. We should rename this to `husk`. Yar? Nar?

**Comment by paulcbetts** [comment]
I'm not super excited about the name `husk`, it's super opaque. Anything better?

**Comment by benogle** [comment]
Husk is great. Available on npm, short in the command line, descriptive, it feels positive.

**Comment by kevinsawicki** [comment]
I'm a big fan of husk, I think with the vision of some CLI tooling for Atom Shell, then it really works as a short, memorable name, that isn't already taken.

**Comment by thedaniel** [comment]
I'm a big fan of explicit names, and would prefer even `atom-shell-bootstrap` to `husk`. As I note in #53 I don't think this repo should imminently become a framework so I think making it clear that it's a collection of stuff to help an atom-shell developer along and not a standalone product is important. So I am :-1: on this.

**Comment by kevinsawicki** [comment]
Closing this out, this repo is no longer actively being worked on so renaming it doesn't seem like something that should happen moving forward.
