### ISSUE TITLE
Javascript version?

### ISSUE THREAD

**Issue by waynebloss** [atom/electron-starter#82]
Hello, I am just wondering if there is a version of this template that is done with Javascript? If not, is one planned?

If neither of those, can I have some advice on transforming this project into Javascript? What tool do I use to convert each file, any special configurations, etc...

Thank you.

**Comment by paulcbetts** [comment]
The next major version of this template will be done in ES6 for sure, and also be far simpler than this one

**Comment by waynebloss** [comment]
Sounds good. I will study this one in the meantime and learn what I can from it. Thanks again.

**Comment by waynebloss** [comment]
Hi @paulcbetts I'm curious if you guys are planning on switching Electron core to Javascript as well or just this project?

**Comment by paulcbetts** [comment]
Electron itself will probably stay in Coffeescript
